// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUUzMVQ4xm-P8OkjY5XKNRU_jPRelGHhk',
    appId: '1:347164430460:web:209fb6f3519c89343e39f9',
    messagingSenderId: '347164430460',
    projectId: 'pushnotificationgithub',
    authDomain: 'pushnotificationgithub.firebaseapp.com',
    storageBucket: 'pushnotificationgithub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_dsYFWfLmRBFnqiSswZjM_U7yr8wz85k',
    appId: '1:347164430460:android:babbb2ba1e727f413e39f9',
    messagingSenderId: '347164430460',
    projectId: 'pushnotificationgithub',
    storageBucket: 'pushnotificationgithub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcFTqUDarC9kXD6ypt_Ft42-iVNTz0T_Y',
    appId: '1:347164430460:ios:2ba1c8d02945112e3e39f9',
    messagingSenderId: '347164430460',
    projectId: 'pushnotificationgithub',
    storageBucket: 'pushnotificationgithub.appspot.com',
    iosBundleId: 'com.example.pushNotificationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcFTqUDarC9kXD6ypt_Ft42-iVNTz0T_Y',
    appId: '1:347164430460:ios:e5723499674a6b1b3e39f9',
    messagingSenderId: '347164430460',
    projectId: 'pushnotificationgithub',
    storageBucket: 'pushnotificationgithub.appspot.com',
    iosBundleId: 'com.example.pushNotificationFirebase.RunnerTests',
  );
}
